use master;
go
use UNIVER;
go

--1 задание 

select FACULTY.FACULTY_NAME,
PROFESSION.PROFESSION_NAME,
avg(PROGRESS.NOTE)[оценка],
PROGRESS.SUBJECT
from FACULTY
	inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
	inner join PROFESSION on PROFESSION.PROFESSION = GROUPS.PROFESSION
	inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
	inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY in ('ИТ')

group by ROLLUP   (FACULTY_NAME, PROFESSION_NAME, PROGRESS.SUBJECT );

--2ое задание


select FACULTY.FACULTY_NAME,
PROFESSION.PROFESSION_NAME,
avg(PROGRESS.NOTE)[оценка],
PROGRESS.SUBJECT
from FACULTY
	inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
	inner join PROFESSION on PROFESSION.PROFESSION = GROUPS.PROFESSION
	inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
	inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where FACULTY.FACULTY in ('ИТ')

group by CUBE   (FACULTY_NAME, PROFESSION_NAME, PROGRESS.SUBJECT );

--задание 3

select FACULTY_NAME,
PROFESSION.PROFESSION_NAME,
SUBJECT, 
avg(NOTE)[оценка] 

from FACULTY
inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
inner join PROFESSION on PROFESSION.PROFESSION = GROUPS.PROFESSION
inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
where PROFESSION.PROFESSION = '1-47 01 01'
group by FACULTY_NAME, PROFESSION_NAME, PROGRESS.SUBJECT

union 

select FACULTY_NAME,
PROFESSION.PROFESSION_NAME,
SUBJECT, 
avg(NOTE)[оценка] 

from FACULTY
inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
inner join PROFESSION on PROFESSION.PROFESSION = GROUPS.PROFESSION
inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
where PROFESSION.PROFESSION = '1-36 06 01'
group by FACULTY_NAME, PROFESSION_NAME, PROGRESS.SUBJECT

--задание 4


select FACULTY_NAME,
PROFESSION.PROFESSION_NAME,
SUBJECT, 
avg(NOTE)[оценка] 

from FACULTY
inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
inner join PROFESSION on PROFESSION.PROFESSION = GROUPS.PROFESSION
inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
where PROFESSION.PROFESSION = '1-47 01 01'
group by FACULTY_NAME, PROFESSION_NAME, PROGRESS.SUBJECT

INTERSECT  

select FACULTY_NAME,
PROFESSION.PROFESSION_NAME,
SUBJECT, 
avg(NOTE)[оценка] 

from FACULTY
inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
inner join PROFESSION on PROFESSION.PROFESSION = GROUPS.PROFESSION
inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
where PROFESSION.PROFESSION = '1-36 06 01'
group by FACULTY_NAME, PROFESSION_NAME, PROGRESS.SUBJECT

--задание 5

select FACULTY_NAME,
PROFESSION.PROFESSION_NAME,
SUBJECT, 
avg(NOTE)[оценка] 

from FACULTY
inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
inner join PROFESSION on PROFESSION.PROFESSION = GROUPS.PROFESSION
inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
where PROFESSION.PROFESSION = '1-47 01 01'
group by FACULTY_NAME, PROFESSION_NAME, PROGRESS.SUBJECT

EXCEPT  

select FACULTY_NAME,
PROFESSION.PROFESSION_NAME,
SUBJECT, 
avg(NOTE)[оценка] 

from FACULTY
inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
inner join PROFESSION on PROFESSION.PROFESSION = GROUPS.PROFESSION
inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT 
where PROFESSION.PROFESSION = '1-36 06 01'
group by FACULTY_NAME, PROFESSION_NAME, PROGRESS.SUBJECT

