use UNIVER;
go 
--задание 1

select AUDITORIUM_TYPE.AUDITORIUM_TYPE, AUDITORIUM.AUDITORIUM 
from AUDITORIUM_TYPE  INNER JOIN  AUDITORIUM
on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;
go

--задание 2

select AUDITORIUM_TYPE.AUDITORIUM_TYPE, AUDITORIUM.AUDITORIUM 
from AUDITORIUM_TYPE  INNER JOIN  AUDITORIUM
on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE and
AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%компьютерный%'
go

--задание 3

select PROGRESS.NOTE, STUDENT.NAME, GROUPS.FACULTY, SUBJECT.SUBJECT_NAME, PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME,
case 
when ( PROGRESS.NOTE between 6 and 8) then ' оценка от 6 до 8 ' 
else ' другая оценка'
end [ шесть, семь, восемь ]
from PROGRESS 
	INNER JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	INNER JOIN GROUPS ON GROUPS.IDGROUP = STUDENT.IDGROUP
	INNER JOIN FACULTY ON FACULTY.FACULTY = GROUPS.FACULTY
	INNER JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
	INNER JOIN SUBJECT ON SUBJECT.SUBJECT = PROGRESS.SUBJECT
	INNER JOIN PULPIT ON PULPIT.PULPIT = SUBJECT.PULPIT
where PROGRESS.NOTE BETWEEN 6 AND 8
order by PROGRESS.NOTE DESC;
go
--задание 4

select isnull (TEACHER.PULPIT, ' *** ') [PULPIT_NAME], [TEACHER_NAME]
from PULPIT LEFT OUTER JOIN  TEACHER
on TEACHER.PULPIT = PULPIT.PULPIT;
go

--задание 6

select AUDITORIUM_TYPE.AUDITORIUM_TYPE, AUDITORIUM.AUDITORIUM 
from AUDITORIUM_TYPE  CROSS JOIN  AUDITORIUM
where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;
go
